<!DOCTYPE html>
<html lang="en">
<head>
    <title>BUYSELL</title>
</head>
<body>
<h1>BUYSELL</h1><hr>
<h4>Регистрация</h4>
<form action="/registration" method="post">
    Логин: <input type="text" name="login"><br><br>
    Пароль: <input type="password" name="Password"><br><br>
    Имя: <input type="text" name="Password"><br><br>
    Фамилия: <input type="text" name="Password"><br><br>
<#--    <input type="hidden" name="_csrf" value="${_csrf.token}">-->
    <input type="submit" value="Вход"/>
</form>
</body>
</html>